# Generated by Django 5.2.1 on 2025-05-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='id_card_picture',
            field=models.ImageField(blank=True, null=True, upload_to='investors/id_cards/'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
