# Generated by Django 5.2.1 on 2025-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_investor_id_card_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
