# Generated by Django 5.2.1 on 2025-06-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_negotiation_investor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiation',
            name='investor',
        ),
    ]
