# Generated by Django 5.2.1 on 2025-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0006_remove_negotiation_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='commercial_register_picture',
            field=models.ImageField(blank=True, null=True, upload_to='investors/commercial/'),
        ),
    ]
