# Generated by Django 5.2.1 on 2025-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0008_investor_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentoffer',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('project_update', 'Project Update'), ('owner_rejected', 'Owner Rejected'), (None, 'No Reason')], max_length=20, null=True),
        ),
    ]
