# Generated by Django 5.2.1 on 2025-07-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0010_investor_auto_rating_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='investor.investmentoffer'),
        ),
    ]
