# Generated by Django 5.2.1 on 2025-07-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0011_alter_negotiation_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentoffer',
            name='rejection_reason',
        ),
    ]
