# Generated by Django 5.2.1 on 2025-07-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0012_remove_investmentoffer_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
