# Generated by Django 5.2.1 on 2025-07-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0013_investor_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='investmentoffer',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
