# Generated by Django 5.2.1 on 2025-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='ahmad', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
