# Generated by Django 5.2.1 on 2025-05-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='project',
            name='equity_percentage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='funding_goal',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('general_trade', 'General Trade'), ('construction', 'Construction'), ('business', 'Business'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='idea_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_solving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='readiness_level',
            field=models.CharField(blank=True, choices=[('idea', 'Idea'), ('prototype', 'Prototype'), ('existing', 'Existing Project')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FeasibilityStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(max_length=255)),
                ('current_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funding_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('marketing_investment_percentage', models.PositiveIntegerField()),
                ('team_investment_percentage', models.PositiveIntegerField()),
                ('expected_monthly_revenue', models.CharField(max_length=255)),
                ('roi_period_months', models.PositiveIntegerField()),
                ('expected_profit_margin', models.CharField(max_length=255)),
                ('market_size', models.CharField(max_length=255)),
                ('growth_opportunity', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_study', to='projectOwner.project')),
            ],
        ),
    ]
