# Generated by Django 5.2.1 on 2025-05-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0002_remove_project_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectowner',
            name='company_name',
        ),
    ]
