# Generated by Django 5.2.1 on 2025-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0003_remove_projectowner_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibilitystudy',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='feasibilitystudy',
            name='market_size',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under_negotiation', 'Under Negotiation'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
