# Generated by Django 5.2.1 on 2025-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0005_projectowner_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilitystudy',
            name='competitive_edge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feasibilitystudy',
            name='market_potential',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feasibilitystudy',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='feasibilitystudy',
            name='risk_assessment',
            field=models.FloatField(default=0),
        ),
    ]
