# Generated by Django 5.2.1 on 2025-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0006_feasibilitystudy_competitive_edge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('under_negotiation', 'Under Negotiation'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
