# Generated by Django 5.2.1 on 2025-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0007_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectowner',
            name='auto_rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='projectowner',
            name='manual_rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='projectowner',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
    ]
