# Generated by Django 5.2.1 on 2025-07-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0009_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilitystudy',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
