# Generated by Django 5.2.1 on 2025-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0010_feasibilitystudy_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pending_changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
