# Generated by Django 5.2.1 on 2025-07-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0011_project_pending_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pending_changes',
        ),
    ]
